# Generated by Django 4.0.3 on 2022-09-26 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=20)),
                ('job_description', models.CharField(max_length=100)),
                ('employer', models.CharField(max_length=20)),
                ('responsibilities', models.CharField(max_length=100)),
                ('job_type', models.CharField(choices=[('part-time', 'part-time'), ('full-time', 'full-time'), ('contract', 'contract')], max_length=10)),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=30)),
                ('zip_code', models.IntegerField()),
            ],
        ),
    ]
