# Generated by Django 4.0.3 on 2022-10-01 04:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 9, 30, 23, 25, 2, 644317)),
        ),
    ]
