# Generated by Django 4.0.3 on 2022-10-01 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Job', '0002_alter_userprofile_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='created_at',
        ),
    ]
