# Generated by Django 4.0.3 on 2022-10-02 01:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job', '0002_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2022, 10, 1, 20, 13, 16, 691468)),
        ),
    ]
