# Generated by Django 4.0.3 on 2022-10-02 07:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job', '0003_alter_post_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='user_porfile',
            new_name='user_profile',
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2022, 10, 2, 2, 43, 15, 371836)),
        ),
    ]
