# Generated by Django 4.0.3 on 2022-10-08 02:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Job', '0004_rename_user_porfile_post_user_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2022, 10, 7, 21, 43, 16, 203418)),
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=100)),
                ('commentor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Job.userprofile')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Job.post')),
            ],
        ),
    ]
