# Generated by Django 4.0.3 on 2022-10-08 02:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job', '0005_alter_post_created_at_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2022, 10, 7, 21, 43, 58, 544915)),
        ),
    ]
